### ISSUE TITLE
Add "HelloWorld" script in python

### ISSUE THREAD

**Issue by dmitry-ed-gusev** [dmitry-ed-gusev/my-learning#1]

**Comment by dmitry-ed-gusev** [comment]
Please, leave a comment...

**Comment by DiMAS256** [comment]
Ок, работаем)

**Comment by DiMAS256** [comment]
Необходимо загрузить программу пайтон Hello world?

**Comment by dmitry-ed-gusev** [comment]
По окончании работы за собой надо закрывать задачи :) @DiMAS256 - закрой эту задачу за собой!

**Comment by dmitry-ed-gusev** [comment]
@DiMAS256 - кстати, не нашел программы с выводом "Hello World!" в master!!! Это надо исправить, прежде чем браться за следующую задачу!
