### ISSUE TITLE
Implement converter utility from DECIMAL to BINARY

### ISSUE THREAD

**Issue by dmitry-ed-gusev** [dmitry-ed-gusev/my-learning#12]
1. Name utility as "dec2bin"
2. The utility should get the decimal number from cmd line arguments (first argument), converts it to a binary number and out it to console
3. If no number provided as an input, the utility should print the message "Please, provide a decimal number for conversion..." and exit
4. If the number provided - convert and print it back to the console

**Comment by dmitry-ed-gusev** [comment]
Привет! Бранч назвал неверно - номер данной задачи 12 - см выше - надпись: #12. Соотв. бранч должен называться ML-12-...... Оставь так, но учти на будущее.

**Comment by DiMAS256** [comment]
Привет!
задача выполнена, прошу проверить.

**Comment by dmitry-ed-gusev** [comment]
ок, как проверю отпишусь 👍

**Comment by dmitry-ed-gusev** [comment]
Done
