### ISSUE TITLE
Implement converter utility from DECIMAL to HEXADECIMAL

### ISSUE THREAD

**Issue by dmitry-ed-gusev** [dmitry-ed-gusev/my-learning#16]
1. Name utility as "dec2hex"
2. The utility should get the decimal number from cmd line arguments (first argument), converts it to a hexadecimal number and out it to console
3. If no number provided as an input, the utility should print the message "Please, provide a decimal number for conversion..." and exit
4. If the number provided - convert and print it back to the console

**Comment by DiMAS256** [comment]
Done
