### ISSUE TITLE
Implement console utility (program) like <cat> linux system command

### ISSUE THREAD

**Issue by dmitry-ed-gusev** [dmitry-ed-gusev/my-learning#7]
1. Google **cat** command properties and description
2. Your program should be named <mycat>
3. Your program should be run as:
     `python3 mycat <filename>`
4. Your program should be able to open **any type of file as simple text**
5. If your program will be run without file name as:
     `python3 mycat`
    program should out text message like: "Please provide a file for printing..."
6. Any Q&A are welcome in the current issue as comments...

**Comment by DiMAS256** [comment]
В 3 пункте говорится о команде (python3 mycat <filename>), она так и пишется? верно?
Просто mycat не видел как команду

**Comment by dmitry-ed-gusev** [comment]
> В 3 пункте говорится о команде (python3 mycat ), она так и пишется? верно?
> Просто mycat не видел как команду

Это имя твоей программы, которую надо написать. Может быть любым, но мне нравится mycat.

**Comment by DiMAS256** [comment]
> 1. Свойства и описание команды Google **cat**
> 2. Ваша программа должна быть названа
> 3. Ваша программа должна быть запущена как:
>    `python3 mycat <filename>`
> 4. Ваша программа должна быть в состоянии открыть **любой тип файла в виде простого текста**
> 5. Если ваша программа будет запущена без имени файла как: 
>    `python3 mycat`
>    программа должна выдать текстовое сообщение вроде: «Пожалуйста, предоставьте файл для печати ...»
> 6. Любые вопросы и ответы приветствуются в текущем выпуске в качестве комментариев ...

в моём понимании в № 3 необходимо создать файл (mycap.py) с кодом cat. Так, что бы после запуска оставалось только ввести название текстового документа?

**Comment by dmitry-ed-gusev** [comment]
Пишу комменты на русском, но в дальнейшем будет не английском! :)
1. удалить папку my-learning из корня - что она там делает??? и откуда взялась???
2. Условие №5 не выполнено - исправить!
3. Оставить ОДНУ версию программы - выбери сам, я бы взял вторую :)
4. в начало программы добавь комментарий - пример покажу.

**Comment by dmitry-ed-gusev** [comment]
Результат работы - созданная программа - осталась в фича ветке, не в мастере - почему?
1. создать пулл-реквест
2. сделать merge в мастер и закрыть фича ветку
Результат работы ВСЕГДА должен в конце работы оказываться в мастере!

**Comment by DiMAS256** [comment]
После какого шага необходимо создавать пулл-реквест?
После проверки ведь или когда думаю сам, что программа написана хорошо.

**Comment by dmitry-ed-gusev** [comment]
Данный бранч еще не закрыт: ML-7-implement-cat-program

**Comment by dmitry-ed-gusev** [comment]
> После какого шага необходимо создавать пулл-реквест?
> После проверки ведь или когда думаю сам, что программа написана хорошо.

Пулл реквест создаешь как работа завершена и одобрена коллегами (в нашем случае - мной :)) Пулл реквест - показатель окончания работы.
